# Generated by Django 2.0.1 on 2018-01-22 12:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=50)),
                ('private', models.BooleanField()),
                ('personal_data', models.BooleanField()),
                ('data_subject', multiselectfield.db.fields.MultiSelectField(choices=[('students', 'Students, applicants'), ('staff', 'Staff, job applicants'), ('alumni', 'Alumni, supporters'), ('research', 'Research participants'), ('patients', 'Patients'), ('supplier', 'Suppliers, professional advisers and consultants'), ('public', 'Members of public')], max_length=55)),
                ('data_category', multiselectfield.db.fields.MultiSelectField(choices=[('personal', 'Personal details'), ('education', 'Education details'), ('employment', 'Employment details'), ('financial', 'Financial details'), ('social', 'Lifestyle and social circumstances'), ('visual', 'Visual images'), ('research', 'Research data'), ('medical', 'Medical records'), ('children', 'Personal data about children under 16'), ('racial', 'Racial or ethic origin'), ('political', 'Political opinions'), ('unions', 'Trade union membership'), ('religious', 'Religious or similar beliefs'), ('health', 'Physical or mental health details'), ('sexual', 'Sexual life and orientation'), ('genetic', 'Genetic information'), ('biometric', 'Biometric information'), ('criminal', 'Criminal proceedings, outcomes and sentences'), ('others', 'Other (please specify)')], max_length=161)),
                ('data_category_others', models.CharField(max_length=255)),
                ('recipients_category', models.CharField(max_length=255)),
                ('recipients_outside_eea', models.BooleanField()),
                ('recipients_outside_eea_who', models.CharField(max_length=255)),
                ('retention', models.CharField(choices=[('<=1', '1 year or less'), ('>1,<=5', '>1 to 5 years'), ('>5,<=10', '>5 to 10 years'), ('>10,<=75', '>10 to 75 years'), ('forever', 'Forever'), ('other', 'Other (please specify)')], max_length=255)),
                ('retention_other', models.CharField(max_length=255)),
                ('risk_type', multiselectfield.db.fields.MultiSelectField(choices=[('financial', 'Financial'), ('operational', 'Operational'), ('compliance', 'Compliance'), ('reputational', 'Reputational'), ('safety', 'Personal Safety')], max_length=52)),
                ('storage_location', models.CharField(max_length=255)),
                ('storage_format', multiselectfield.db.fields.MultiSelectField(choices=[('digital', 'Digital'), ('paper', 'Paper')], max_length=13)),
                ('paper_storage_security', multiselectfield.db.fields.MultiSelectField(choices=[('locked_cabinet', 'Locked filing cabinet'), ('safe', 'Safe'), ('locked_room', 'Locked room'), ('locked_building', 'Locked building')], max_length=47)),
                ('digital_storage_security', multiselectfield.db.fields.MultiSelectField(choices=[('pwd_controls', 'Password controls'), ('acl', 'Access control lists'), ('backup', 'Backup'), ('encryption', 'Encryption')], max_length=34)),
            ],
        ),
    ]
