# Generated by Django 2.0.1 on 2018-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180202_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='private',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
