# Generated by Django 2.0.1 on 2018-02-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180213_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purpose',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
