# Generated by Django 2.0.1 on 2018-02-14 11:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180214_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='retention_other',
        ),
        migrations.AlterField(
            model_name='asset',
            name='digital_storage_security',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[('pwd_controls', 'Password controls'),
                                     ('acl', 'Access control lists'),
                                     ('backup', 'Backup'), ('encryption', 'Encryption'),
                                     ('none', 'None of the above')],
                db_index=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='paper_storage_security',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[('locked_cabinet', 'Locked filing cabinet'),
                                     ('safe', 'Safe'), ('locked_room', 'Locked room'),
                                     ('locked_building', 'Locked building'),
                                     ('none', 'None of the above')],
                db_index=True, max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='retention',
            field=models.CharField(blank=True, choices=[('<1', 'Less than 1 year'),
                                                        ('>=1,<=5', '1 to 5 years'),
                                                        ('>5,<=10', '5 to 10 years'),
                                                        ('>10,<=75', '10 to 75 years'),
                                                        ('forever', 'Forever')],
                                   db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_type',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[('financial', 'Financial'), ('operational', 'Operational'),
                                     ('compliance', 'Compliance'),
                                     ('reputational', 'Reputational'),
                                     ('safety', 'Personal Safety'),
                                     ('none', 'None of the above')],
                db_index=True, max_length=57, null=True),
        ),
    ]
