# Generated by Django 2.0.1 on 2018-02-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='purpose',
            new_name='purpose_other',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='recipients_category',
            new_name='recipients_outside_uni_description',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='recipients_outside_eea',
            new_name='recipients_outside_eea_description',
        ),
    ]
