# Generated by Django 2.0.1 on 2018-02-26 10:47

from django.db import migrations, models
from django.db.models import Q


def set_recipients_yes_choice_if_recipients_given(apps, schema_editor):
    """
    Set the recipients choice to 'yes' if recipients text is given,
    for both UNI and EEA respectively.
    """
    Asset = apps.get_model('assets', 'Asset')
    for asset in Asset.objects.filter(recipients_outside_uni_description__isnull=False):
        asset.recipients_outside_uni = 'yes'
        asset.save()
    for asset in Asset.objects.filter(recipients_outside_eea_description__isnull=False):
        asset.recipients_outside_eea = 'yes'
        asset.save()


def set_purpose_choice(apps, schema_editor):
    """
    Set the purpose choice to 'other' if purpose text is given
    or 'research' if research flag is set.
    """
    Asset = apps.get_model('assets', 'Asset')
    for asset in Asset.objects.filter(Q(purpose_other__isnull=False) | Q(research=True)):
        if asset.research:
            asset.purpose = 'research'
            # TODO possible loss of data here
            asset.purpose_other = None
        elif asset.purpose_other is not None:
            asset.purpose = 'other'
        asset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20180226_1047'),
    ]

    operations = [
        # workaround to recreate the purpose_other index with the correct name
        migrations.AlterField(
            model_name='asset',
            name='purpose_other',
            field=models.TextField(blank=True, db_index=False, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purpose_other',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        # workaround to recreate the recipients_outside_uni_description index with the correct name
        migrations.AlterField(
            model_name='asset',
            name='recipients_outside_uni_description',
            field=models.TextField(blank=True, db_index=False, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='recipients_outside_uni_description',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        # workaround to recreate the recipients_outside_eea_description index with the correct name
        migrations.AlterField(
            model_name='asset',
            name='recipients_outside_eea_description',
            field=models.TextField(blank=True, db_index=False, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='recipients_outside_eea_description',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purpose',
            field=models.CharField(blank=True, choices=[('teaching', 'Teaching'), ('research', 'Research'), ('student_administration', 'Student administration'), ('staff_administration', 'Staff administration (HR)'), ('alumni_supporter_administration', 'Alumni/supporter administration'), ('supplier_customer_administration', 'Supplier/customer administration'), ('financial_estate_administration', 'Financial/estate administration'), ('governance_compliance', 'Governance/compliance'), ('security', 'Security'), ('marketing', 'Marketing'), ('public_engagement', 'Public engagement'), ('other', 'Other')], db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='recipients_outside_uni',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not Sure')], db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='recipients_outside_eea',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not Sure')], db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_type_additional',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(set_recipients_yes_choice_if_recipients_given),
        migrations.RunPython(set_purpose_choice),
        migrations.RemoveField(
            model_name='asset',
            name='research',
        ),
    ]
