# Generated by Django 2.0.2 on 2018-03-06 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('assets', '0008_auto_20180227_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLookup',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lookup', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('scheme', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
            ],
        ),
    ]
