# Generated by Django 2.0.1 on 2018-03-12 10:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_userlookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='data_category',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[('education', 'Education details'),
                                     ('alumni', 'Alumni records'),
                                     ('contact', 'Basic contact details'),
                                     ('employment', 'Employment details'),
                                     ('financial', 'Financial details'),
                                     ('social', 'Lifestyle and social circumstances'),
                                     ('visual', 'Visual images'),
                                     ('research', 'Research data'),
                                     ('medical', 'Medical records'),
                                     ('children', 'Personal data about children under 16'),
                                     ('racial', 'Racial or ethic origin'),
                                     ('political', 'Political opinions'),
                                     ('unions', 'Trade union membership'),
                                     ('religious', 'Religious or similar beliefs'),
                                     ('health', 'Physical or mental health details'),
                                     ('sexual', 'Sexual life and orientation'),
                                     ('genetic', 'Genetic information'),
                                     ('biometric', 'Biometric information'),
                                     ('criminal', 'Criminal proceedings, outcomes and sentences')],
                db_index=True, max_length=160, null=True),
        ),
    ]
