# Generated by Django 2.0.1 on 2018-03-15 11:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20180312_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='data_category',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[('education', 'Education records'),
                                     ('alumni', 'Alumni records'),
                                     ('contact', 'Basic contact details'),
                                     ('employment', 'Employment records'),
                                     ('financial', 'Financial details'),
                                     ('social', 'Lifestyle and social circumstances'),
                                     ('visual', 'Visual images'),
                                     ('research', 'Research data'),
                                     ('medical', 'Medical records'),
                                     ('children', 'Personal data about children under 16'),
                                     ('racial', 'Racial or ethic origin'),
                                     ('political', 'Political opinions'),
                                     ('unions', 'Trade union membership'),
                                     ('religious', 'Religious or similar beliefs'),
                                     ('health', 'Physical or mental health details'),
                                     ('sexual', 'Sexual life and orientation'),
                                     ('genetic', 'Genetic information'),
                                     ('biometric', 'Biometric information'),
                                     ('criminal', 'Criminal proceedings, outcomes and sentences')],
                db_index=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purpose',
            field=models.CharField(
                blank=True,
                choices=[('teaching', 'Teaching'),
                         ('research', 'Research (Academic)'),
                         ('research_organisational', 'Research (Organisational)'),
                         ('student_administration', 'Student administration'),
                         ('staff_administration', 'Staff administration (HR)'),
                         ('alumni_supporter_administration', 'Alumni/supporter administration'),
                         ('supplier_customer_administration', 'Supplier/customer administration'),
                         ('financial_estate_administration', 'Financial/estate administration'),
                         ('governance_compliance', 'Governance/compliance'),
                         ('security', 'Security'), ('marketing', 'Marketing'),
                         ('public_engagement', 'Public engagement'), ('other', 'Other')],
                db_index=True, max_length=255, null=True),
        ),
    ]
