# Generated by Django 2.0.4 on 2018-04-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20180315_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlookup',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserLookup',
        ),
    ]
